spring.application.name=personal-notebook

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_notebook_db
spring.datasource.username=postgres
spring.datasource.password=
# Replace 'root' with your actual pgAdmin/PostgreSQL password.

# Thymeleaf caching for development
spring.thymeleaf.cache=false

# Error handling
server.error.include-message=always
